mysql:
    host: 127.0.0.1
    port: "3306"
    db: test
    user: root
    password: chenyijun
    log_level: env
logger:
    level: info
    prefix: '[ginBlog]'
    director: log
    show-line: true
    log_in_console: ""
system:
    host: 127.0.0.1
    port: "8090"
    env: release
site_info:
    create_at: "11111"
email:
    level: ""
    port: 56782222
    user: ""
    password: ""
    default_from_email: ""
    use_ssl: false
    user_tls: false
qq:
    app_id: xxx
    key: xx
    redirect: http://xx.xx.com/login?flag=qq
jwt:
    secret: xxx
    expires: 48
    issuer: xx
qiniu:
    enable: false
    access_key: UMM-xx-FdRif-xx
    secret_key: xx
    bucket: xiugo
    cdn: xx://xx.xx.com/
    zone: xx
    size: 5
file_settings:
    type:
        - "jpg"
        - "png"
        - "jpeg"
        - "gif"
        - "ico"
        - "tiff"
        - "webp"
    size: 5
    path: template/upload_files
